const COMMON_ERROR = Object.freeze({
  ACTION_NOT_FOUND: 'ACTION_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  OPENID_MISSING: 'OPENID_MISSING',
  PERMISSION_DENIED: 'PERMISSION_DENIED'
})

module.exports = {
  COMMON_ERROR
}
